### ISSUE TITLE
Allow choice of endpoints in query notebook

### ISSUE THREAD

**Issue by AlasdairGray** [AlasdairGray/IDPcentral#17]
The RDFlib approach is fine for small datasets but starts to struggle with the sample-25 and really doesn't cope with the full dataset.

@ImranAsif48 can you add an option at the start of the notebook that allows you to select between local in memory execution or a user specified endpoint?

It is likely that each and every query will need to be updated. It would also be worth adding in a log statement to say what query is being executed and then how many results are returned.

- [x] Allow choice of endpoint
- [x] Log location of endpoint
- [x] Add log messages before and after each query
- [x] Allow selection between different data samples
- [x] Move all queries to files
- [x] Read each query in from file in the appropriate point in the notebook
- [x] Log which query is being executed
  - [x] info level could just be query file
  - [x] debug level could log the query text
- [x] Log result size
- [x] Add button to collapse/expand (show/hide) query
- [x] Use query description for dropdown choice instead of filename

**Comment by AlasdairGray** [comment]
Note that the Full Protein Information query will not run on a standards compliant endpoint. It returns variables that are not in the `GROUP BY` clause. This is because RDFlib returns an error if there are no bindings for a `GROUP_CONCAT`. The correct query should be
```sparql
PREFIX schema: <https://schema.org/>
PREFIX pav: <http://purl.org/pav/>
PREFIX void: <http://rdfs.org/ns/void#>

SELECT  ?s 
    (GROUP_CONCAT(DISTINCT ?name;SEPARATOR=',<br/>') AS ?names)
    (GROUP_CONCAT(DISTINCT ?description;SEPARATOR=',<br/>') AS ?descriptions)
    (GROUP_CONCAT(DISTINCT ?identifier;SEPARATOR=',<br/>') AS ?identifiers)
    (GROUP_CONCAT(DISTINCT ?associatedDisease;SEPARATOR=',<br/>') AS ?diseases)
    (GROUP_CONCAT(DISTINCT ?annotation;SEPARATOR=',<br/>') AS ?annotations)
    (GROUP_CONCAT(DISTINCT ?encodedBy;SEPARATOR=',<br/>') AS ?genes)
    (GROUP_CONCAT(DISTINCT ?taxonomicRange;SEPARATOR=',<br/>') AS ?taxons)
    (GROUP_CONCAT(DISTINCT ?url;SEPARATOR=',<br/>') AS ?urls)
    (GROUP_CONCAT(DISTINCT ?alternateName;SEPARATOR=',<br/>') AS ?altNames)
    (GROUP_CONCAT(DISTINCT ?bioChemInteraction;SEPARATOR=',<br/>') AS ?interactions)
    (GROUP_CONCAT(DISTINCT ?bioChemSimilarity;SEPARATOR=',<br/>') AS ?similarTo)
    (GROUP_CONCAT(DISTINCT ?bioChemEntity;SEPARATOR=',<br/>') AS ?entities)
    (GROUP_CONCAT(DISTINCT ?sequence;SEPARATOR=',<br/>') AS ?sequences)
    (GROUP_CONCAT(DISTINCT ?molFunction;SEPARATOR=',<br/>') AS ?functions)
    (GROUP_CONCAT(DISTINCT ?representation;SEPARATOR=',<br/>') AS ?representations)
    (GROUP_CONCAT(DISTINCT ?image;SEPARATOR=',<br/>') AS ?images)
    (GROUP_CONCAT(DISTINCT ?process;SEPARATOR=',<br/>') AS ?processes)
    (GROUP_CONCAT(DISTINCT ?cellularLocation;SEPARATOR=',<br/>') AS ?locations)
    (GROUP_CONCAT(DISTINCT ?parentEntity;SEPARATOR=',<br/>') AS ?parents)
    (GROUP_CONCAT(DISTINCT ?sameAs;SEPARATOR=',<br/>') AS ?sameAs_s)
    (GROUP_CONCAT(DISTINCT ?source;SEPARATOR=',<br/>') AS ?sources)
    (GROUP_CONCAT(DISTINCT ?dataset;SEPARATOR=',<br/>') AS ?datasets)
WHERE {
    GRAPH ?g {
# Bioschemas Minimal Properties
        ?s a schema:Protein .
        OPTIONAL {?s schema:identifier ?identifier }
        OPTIONAL {?s schema:name ?name }
## Bioschemas Recommended properties
        OPTIONAL {?s schema:associatedDisease ?associatedDisease}
        OPTIONAL {?s schema:description ?description}
        #OPTIONAL 
        {?s schema:hasSequenceAnnotation ?annotation }
        OPTIONAL {?s schema:isEncodedByBioChemEntity ?encodedBy}
        OPTIONAL {?s schema:taxonomicRange ?taxonomicRange }
        OPTIONAL {?s schema:url ?url}
## Bioschemas Optional properties
        OPTIONAL {?s schema:alternateName ?alternateName}
        OPTIONAL {?s schema:bioChemInteraction ?bioChemInteraction}
        OPTIONAL {?s schema:bioChemSimilarity ?bioChemSimilarity}
        OPTIONAL {?s schema:hasBioChemEntityPart ?bioChemEntity}
        OPTIONAL {?s schema:hasBioPolymerSequence ?sequence}
        OPTIONAL {?s schema:hasMolecularFunction ?molFunction}
        OPTIONAL {?s schema:hasRepresentation ?representation }
        OPTIONAL {?s schema:image ?image}
        OPTIONAL {?s schema:isInvolvedInBiologicalProcess ?process}
        OPTIONAL {?s schema:isLocatedInSubcellularLocation ?cellularLocation}
        OPTIONAL {?s schema:isPartOfBioChemEntity ?parentEntity}
        OPTIONAL {?s schema:sameAs ?sameAs }
    }
    ?g pav:retrievedFrom ?source ;
    OPTIONAL {?g void:inDataset ?dataset}
}
GROUP BY ?s
```

**Comment by AlasdairGray** [comment]
@ImranAsif48 you may also want to think about reading the queries in from the files in the query directory, that would then solve #11 at the same time.

**Comment by ImranAsif48** [comment]
@AlasdairGray I just updated the AnalysisQueries.ipynb file with the choice of endpoints and local. After the button clicks, all select queries from query directory will run. Please test it.

**Comment by AlasdairGray** [comment]
- [ ] Move all queries to files
- [ ] Read each query in from file in the appropriate point in the notebook
- [ ] Log result size

**Comment by ImranAsif48** [comment]
I updated the options now.

**Comment by AlasdairGray** [comment]
I've added the query to answer #12 to the notebook, using the new run query method. However, something seems to be up about the order that result columns are being processed. In the screenshot below the header columns do not correspond with the data columns.
<img width="277" alt="Screenshot 2021-09-02 at 20 15 02" src="https://user-images.githubusercontent.com/1141265/131903316-c9b8fbeb-552e-4276-bc20-9f98fbc29a5b.png">

**Comment by ImranAsif48** [comment]
@AlasdairGray Hi, I made all the changes in this version. I proposed the solution that how to execute the query in order. If this solution is good then remove the remaining cells (contains queries) of jupyter. I also updated all queries in the query directory and also add new file if there was not in directory. Please have a look.

**Comment by AlasdairGray** [comment]
Thanks for doing that. We'll need to think how we structure the notebook now since it is no longer providing a narrative through the queries.

**Comment by ImranAsif48** [comment]
@AlasdairGray I updated the notebook and one query that had the issue. Please have a look. Thanks
