### ISSUE TITLE
Query 18 won't run from Notebook

### ISSUE THREAD

**Issue by AlasdairGray** [AlasdairGray/IDPcentral#20]
@ImranAsif48 please can you verify if this works for you.

I tried running query 18 'Query to analyse the number of proteins by dataset groups' from the notebook to my local GraphDB endpoint loaded with the latest full scrape dataset. I get the following error
```
Exception: QueryBadFormed: a bad request has been sent to the endpoint, probably the sparql query is bad formed.
```
When I copy and paste the query text into the GraphDB query form it runs fine.

**Comment by ImranAsif48** [comment]
@AlasdairGray Bug fixed. The issue was long text query exceed the limit of header. Therefore, need to pass query as POST request. Now it is working fine.
